### ISSUE TITLE
Build error occurred

### ISSUE THREAD

**Issue by xcoincoder** [BHONetwork/bholdus-web#361]
Chao add
Minh build bi loi nhu the nay

Build error occurred
FetchError: request to http://127.0.0.1:1337/pages?status=published failed, reason: connect ECONNREFUSED 127.0.0.1:1337

**Comment by naviocean** [comment]
@xcoincoder bạn cần chạy backend cms trước khi chạy frontend. CMS backend bạn có thể dùng strapi

**Comment by nbtcash** [comment]
Use node 14
and ruby 3.1.2
https://vegastack.com/tutorials/how-to-install-strapi-on-ubuntu-18-04/

**Comment by 0x00trust** [comment]
Chào add
Mình cài strapi thành công lên heroku.com làm backend rồi.
Giờ đưa web này lên vercel.com và làm sao để kết nối tới strapi bên heroku?
Sửa file .env à?

**Comment by 0x00trust** [comment]
Bên render.com cũng hỗ trợ strapi làm backend
Nhưng không biết là bholdus-web sẽ là Web Service hay Static Site
Mình đang deploy dạng Static Site và thử kết nối 2 cái này với nhau trong render.com không biết có được không

**Comment by vuicash** [comment]
> @xcoincoder bạn cần chạy backend cms trước khi chạy frontend. CMS backend bạn có thể dùng strapi

Admin share cho vui thôi chứ không dùng được đâu
Vì cần viết lại toàn bộ backend (strapi) theo frontend.
Đây chỉ là cái template
Thà admin share cái html cho anh em dễ hiểu.

**Comment by vuicash** [comment]
> Chào add Mình cài strapi thành công lên heroku.com làm backend rồi. Giờ đưa web này lên vercel.com và làm sao để kết nối tới strapi bên heroku? Sửa file .env à?

Không chạy được nhé bạn.
Vì bạn cần làm backend
Ví dụ như cái này họ share cả backend và frontend 
https://strapi.io/starters/strapi-starter-next-js-corporate
Bạn vào admin sẽ thấy họ làm rất nhiều thứ mới có thể hiển thị ra frontend 
Khi nào bạn thực sự giỏi backend thì mới viết để chạy cái này được.
Một người giỏi backend để làm thì cũng mất ít nhất vài giờ để build cái này chạy được
Trừ khi được share backend bạn mới deploy cho nó chạy

**Comment by naviocean** [comment]
> Bên render.com cũng hỗ trợ strapi làm backend Nhưng không biết là bholdus-web sẽ là Web Service hay Static Site Mình đang deploy dạng Static Site và thử kết nối 2 cái này với nhau trong render.com không biết có được không

Trong  file `.env` bạn có thể dùng luôn backend của bho.network hiện tại bằng cách set
```BACKEND_URL=https://cms.bho.network```

**Comment by 0x00trust** [comment]
> > Bên render.com cũng hỗ trợ strapi làm backend Nhưng không biết là bholdus-web sẽ là Web Service hay Static Site Mình đang deploy dạng Static Site và thử kết nối 2 cái này với nhau trong render.com không biết có được không
> 
> Trong file `.env` bạn có thể dùng luôn backend của bho.network hiện tại bằng cách set `BACKEND_URL=https://cms.bho.network`



Error occurred prerendering page "/vi/blog". Read more: https://nextjs.org/docs/messages/prerender-error
--
12:50:39 | TypeError: Cannot read properties of undefined (reading 'topic')
12:50:39 | at FeatureArticle (/vercel/path0/.next/server/chunks/705.js:52:36)

**Comment by 0x00trust** [comment]
Sau khi xoá ngôn ngữ tiếng Việt thì buid được rồi admin
Demo 
https://nbtweb.vercel.app/
